//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObjectSpyExtension.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ObjectSpyExtension.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //Recursively loop through DOM elements and assign properties to object
        ///function treeHTML(element, object, currentWindow) {
        ///    if (element) {
        ///        object[&quot;type&quot;] = element.nodeName.toLowerCase();
        ///        object[&quot;attributes&quot;] = {};
        ///        if (element.attributes != null) {
        ///            if (element.attributes.length) {
        ///                for (var i = 0; i &lt; element.attributes.length; i++) {
        ///                    if ((element.attributes[i].value !== &apos;&apos;) &amp;&amp; (element.attributes[i].value != null) &amp;&amp; (elemen [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string common {
            get {
                return ResourceManager.GetString("common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var needPost = true;
        ///var isParentReady = false;
        ///
        ///$(&apos;document&apos;).ready(function () {
        ///    // if window is top page
        ///    if (window.location === window.parent.location) {
        ///        setInterval(function () {
        ///            if (needPost) {
        ///                console.log(&apos;Start posting&apos;);
        ///                postDomMap(qAutomate_server_url, createDomMap());
        ///                needPost = false;
        ///                console.log(&apos;End posting&apos;);
        ///            }
        ///        }, 5000);
        ///    } else {
        ///        var sendDomMapInterval = s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dom_collector {
            get {
                return ResourceManager.GetString("dom_collector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (function() {
        ///	//GLOBALS
        ///	var gHoverElement;		//whatever element the mouse is over
        ///	
        ///	//extended	
        ///	var infoDiv;		//currently just container for InfoDivHover, might add more here
        ///	var infoDivHover;	//container for hoverText text node.
        ///	var hoverText;		//show information about current element that the mouse is over
        ///	
        ///	var currentEventOrigin;
        ///		
        ///	if (!window.console) console = {log: function() {
        ///	}};
        ///	//START
        ///	SetupDOMSelection();	
        ///	
        ///	//(Section 1) Element Selection
        ///	function SetupDOMSelection [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dom_inspector {
            get {
                return ResourceManager.GetString("dom_inspector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! jQuery v1.11.2 | (c) 2005, 2014 jQuery Foundation, Inc. | jquery.org/license */
        ///!function(a,b){&quot;object&quot;==typeof module&amp;&amp;&quot;object&quot;==typeof module.exports?module.exports=a.document?b(a,!0):function(a){if(!a.document)throw new Error(&quot;jQuery requires a window with a document&quot;);return b(a)}:b(a)}(&quot;undefined&quot;!=typeof window?window:this,function(a,b){var c=[],d=c.slice,e=c.concat,f=c.push,g=c.indexOf,h={},i=h.toString,j=h.hasOwnProperty,k={},l=&quot;1.11.2&quot;,m=function(a,b){return new m.fn.init(a,b)},n=/^[\s\uFEFF\xA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_1_11_2_min {
            get {
                return ResourceManager.GetString("jquery_1_11_2_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * jQuery Color Animations v@VERSION
        /// * https://github.com/jquery/jquery-color
        /// *
        /// * Copyright jQuery Foundation and other contributors
        /// * Released under the MIT license.
        /// * http://jquery.org/license
        /// *
        /// * Date: @DATE
        /// */
        ///(function( jQuery, undefined ) {
        ///
        ///	var stepHooks = &quot;backgroundColor borderBottomColor borderLeftColor borderRightColor borderTopColor color columnRuleColor outlineColor textDecorationColor textEmphasisColor&quot;,
        ///
        ///	// plusequals test for += 100 -= 100
        ///	rplusequals = /^([\-+] [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_color {
            get {
                return ResourceManager.GetString("jquery_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! JSON v3.3.2 | http://bestiejs.github.io/json3 | Copyright 2012-2014, Kit Cambridge | http://kit.mit-license.org */
        ///(function(){function N(p,r){function q(a){if(q[a]!==w)return q[a];var c;if(&quot;bug-string-char-index&quot;==a)c=&quot;a&quot;!=&quot;a&quot;[0];else if(&quot;json&quot;==a)c=q(&quot;json-stringify&quot;)&amp;&amp;q(&quot;json-parse&quot;);else{var e;if(&quot;json-stringify&quot;==a){c=r.stringify;var b=&quot;function&quot;==typeof c&amp;&amp;s;if(b){(e=function(){return 1}).toJSON=e;try{b=&quot;0&quot;===c(0)&amp;&amp;&quot;0&quot;===c(new t)&amp;&amp;&apos;&quot;&quot;&apos;==c(new A)&amp;&amp;c(u)===w&amp;&amp;c(w)===w&amp;&amp;c()===w&amp;&amp;&quot;1&quot;===c(e)&amp;&amp;&quot;[1]&quot;==c([ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string json3_min {
            get {
                return ResourceManager.GetString("json3_min", resourceCulture);
            }
        }
    }
}
