package com.kms.katalon.selenium.ide;

import java.io.File;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.regex.Matcher;

import org.apache.commons.lang3.StringUtils;

import com.kms.katalon.selenium.ide.format.ChooseCancelOnNextPromptFormatter;
import com.kms.katalon.selenium.ide.format.DefaultFormatter;
import com.kms.katalon.selenium.ide.format.EchoFormatter;
import com.kms.katalon.selenium.ide.format.Formatter;
import com.kms.katalon.selenium.ide.format.PauseFormatter;
import com.kms.katalon.selenium.ide.format.SendKeysFormatter;
import com.kms.katalon.selenium.ide.format.StoreFormatter;
import com.kms.katalon.selenium.ide.format.VerifyAndAssertFormatter;
import com.kms.katalon.selenium.ide.format.WaitForFormatter;
import com.kms.katalon.selenium.ide.model.Command;
import com.kms.katalon.selenium.ide.model.TestCase;

public final class SeleniumIdeFormatter {
	
	private static final String DATE_FORMAT = "dd-MMM-yyyy hh:mm:ss a";
	
	private String email;

	private static final SeleniumIdeFormatter INSTANCE = new SeleniumIdeFormatter();
	
	private final Map<String, Formatter> formatters = new LinkedHashMap<>();
	
	{
		formatters.put("assert", new VerifyAndAssertFormatter("assert"));
		formatters.put("verify", new VerifyAndAssertFormatter("verify"));
		formatters.put("store", new StoreFormatter());
		formatters.put("sendKeys", new SendKeysFormatter());
		formatters.put("chooseCancelOnNextPrompt", new ChooseCancelOnNextPromptFormatter());
		
		formatters.put("waitForPageToLoad", new DefaultFormatter());
		formatters.put("waitForCondition", new DefaultFormatter());
		formatters.put("waitForFrameToLoad", new DefaultFormatter());
		formatters.put("waitForPopUp", new DefaultFormatter());
		
		formatters.put("waitFor", new WaitForFormatter());
		
		formatters.put("echo", new EchoFormatter());
		formatters.put("pause", new PauseFormatter());
		formatters.put("default", new DefaultFormatter());
	}
	
	public static SeleniumIdeFormatter getInstance() {
        return INSTANCE;
    }

	public String format(TestCase testCase) {
		StringBuilder builder = new StringBuilder();
		builder.append(getHeader(testCase));
		
		List<String> commands = formatCommands(testCase.getCommands());
		commands.forEach(c -> builder.append(c));
		
		builder.append(getFooter(testCase));
		return builder.toString();
	}
	
	public List<String> formatCommands(List<Command> commands) {
		List<String> formattedCommands = new ArrayList<>();
		commands.forEach(command -> {
			String formatted = formatCommand(command);
			formattedCommands.add(formatted);
		});
		return formattedCommands;				
	}
	
	public String formatCommand(Command command) {
		Formatter formatter = getFormatter(command.getCommand());
		if (formatter == null) {
			return String.format("Method %s is not found", command.getCommand());
		}
		String comment = String.format("\n\"%s | %s | %s\"\n", 
				encodeString(command.getCommand()), 
				encodeString(command.getTarget()), 
				encodeString(command.getValue()));
		String formatted = formatter.format(command);
		if (StringUtils.isBlank(formatted)) {
			return String.format("Method %s is not found\n", command.getCommand());
		}
		return comment + formatted;
	}

	public String getHeader(TestCase testCase) {
		StringBuffer buffer = new StringBuffer();
		buffer.append(  "import com.kms.katalon.core.webui.driver.DriverFactory as DriverFactory\n\n" +
						"import com.thoughtworks.selenium.Selenium\n" +
						"import org.openqa.selenium.firefox.FirefoxDriver\n" +
						"import org.openqa.selenium.WebDriver\n" +
						"import com.thoughtworks.selenium.webdriven.WebDriverBackedSelenium\n" +
						"import com.thoughtworks.selenium.webdriven.ElementFinder\n" +
						"import com.thoughtworks.selenium.webdriven.JavascriptLibrary\n" +
						"import static org.junit.Assert.*\n" +
						"import java.util.regex.Pattern\n" +
						"import static org.apache.commons.lang3.StringUtils.join\n\n");
		buffer.append("'----------------------------------------------------'\n");
		buffer.append("'This test case script is generated by Katalon Studio'\n");
		buffer.append(String.format("'Generated date: %s'\n", getCurrentDateTime()));
		buffer.append(String.format("'File path: %s'\n", encodeString(testCase.getFilePath())));
		buffer.append(String.format("'Generated by user email: %s'\n", this.email));
		buffer.append("'----------------------------------------------------'\n\n");
		buffer.append("String baseUrl = \""+ testCase.getBaseUrl() +"\"\n\n");
		buffer.append("WebUI.openBrowser(baseUrl)\n\n");
		buffer.append("driver = DriverFactory.getWebDriver()\n");
		buffer.append("selenium = new WebDriverBackedSelenium(driver, baseUrl)\n");
		buffer.append("javascriptLibrary = new JavascriptLibrary()\n");
		buffer.append("elementFinder = new ElementFinder(javascriptLibrary)\n");
		return buffer.toString();
	}

	public String getFooter(TestCase testCase) {
		return "\nWebUI.closeBrowser()";
	}
	
	private String encodeString(String filePath) {
		return filePath.replace("\\", Matcher.quoteReplacement(File.separator))
				.replace("/", Matcher.quoteReplacement(File.separator));
	}
	
	private String getCurrentDateTime() {
		SimpleDateFormat formatter = new SimpleDateFormat(DATE_FORMAT);
        return formatter.format(Calendar.getInstance().getTime());
	}
	
	private Formatter getFormatter(String command) {
		if (StringUtils.isBlank(command)) {
			return null;
		}
		for (Map.Entry<String, Formatter> entry : formatters.entrySet()) {
		    String key = entry.getKey();
		    Formatter formatter = entry.getValue();
		    if (command.contains(key)) {
		    	return formatter;
		    }
		}
		return formatters.get("default");
	}

	public void setEmail(String email) {
		this.email = email;
	}
	
	public String getEmail() {
		return email;
	}
}
